export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ar">
      <body
        style={{
          margin: '0',
          padding: '0',
          display: 'flex',
        }}
      >{children}</body>
    </html>
  )
}
